import type { Field, FieldId } from "./intake.ts";

export const healthTopics = [
  { id: "current", title: "Current health" },
  { id: "past", title: "Past care" },
  { id: "family", title: "Family history" },
  { id: "lifestyle", title: "Daily life" },
  { id: "providers", title: "Your care team" },
];

type HealthQuestion = Field & { question: string; topic: string };
const question = (
  id: FieldId,
  label: string,
  topic: string,
  prompt: string,
  hint: string,
  required = false,
): HealthQuestion => ({
  id,
  label,
  topic,
  question: prompt,
  placeholder: hint,
  group: "health",
  required,
});
export const healthFields: HealthQuestion[] = [
  question(
    "medications",
    "Current medications",
    "current",
    "What medications, vitamins, or supplements do you take?",
    "Include name, dose if known, and how often. You can say none or unknown.",
    true,
  ),
  question(
    "allergies",
    "Allergies",
    "current",
    "Do you have any allergies or reactions we should know about?",
    "Include medications, foods, latex, contrast, or adhesives and what reaction you had.",
    true,
  ),
  question(
    "currentSymptoms",
    "Other current symptoms",
    "current",
    "What other symptoms are you experiencing?",
    "Describe any symptoms beyond your main reason for visiting, or say none.",
  ),
  question(
    "ros",
    "Review of systems",
    "current",
    "Have you noticed any other recent changes in your health?",
    "Examples: vision, hearing, breathing, digestion, urination, skin, energy, mood, or balance. Share only what applies.",
  ),
  question(
    "history",
    "Medical history",
    "past",
    "What medical conditions have you been told you have?",
    "Include ongoing or past conditions, approximate dates if known, or none.",
    true,
  ),
  question(
    "surgeries",
    "Surgical history",
    "past",
    "Have you had any surgeries or procedures?",
    "Tell us the procedure, area of the body, and approximate year, if you know them.",
    true,
  ),
  question(
    "hospitalizations",
    "Hospitalizations",
    "past",
    "Have you been admitted to a hospital?",
    "Include the reason and approximate date, or say none.",
    true,
  ),
  question(
    "priorInjuries",
    "Previous injuries",
    "past",
    "Have you had significant injuries or similar problems before?",
    "Describe what happened, when, and whether you still have symptoms.",
  ),
  question(
    "priorTreatment",
    "Previous treatment",
    "past",
    "What have you tried for this concern, and did it help?",
    "Include medicines, therapy, injections, or other care in your own words.",
  ),
  question(
    "imaging",
    "Prior imaging or tests",
    "past",
    "Have you had imaging or tests for this concern?",
    "Include the type, approximate date, and where it was done. Results can be unknown.",
  ),
  question(
    "familyHistory",
    "Family medical history",
    "family",
    "Do any health conditions run in your family?",
    "Tell us which relative, the condition, and age when it began if known. Include parents, siblings, children, or grandparents. None, unknown, and prefer not to answer are all accepted.",
    true,
  ),
  question(
    "tobacco",
    "Tobacco & nicotine",
    "lifestyle",
    "Do you currently use, or have you previously used, tobacco or nicotine?",
    "Include smoking, vaping, smokeless tobacco, amount, and quit date if relevant.",
  ),
  question(
    "alcohol",
    "Alcohol use",
    "lifestyle",
    "Do you drink alcohol?",
    "If so, about how much and how often? You may prefer not to answer.",
  ),
  question(
    "substances",
    "Other substance use",
    "lifestyle",
    "Are there other substances your care team should know you use?",
    "Include cannabis or other substances, frequency if relevant, or prefer not to answer.",
  ),
  question(
    "occupation",
    "Occupation & work duties",
    "lifestyle",
    "What kind of work do you do?",
    "Include lifting, prolonged sitting or standing, and any work limitations.",
  ),
  question(
    "exercise",
    "Activity & exercise",
    "lifestyle",
    "What physical activities or exercise do you usually do?",
    "Tell us the activity, frequency, and anything your symptoms prevent you from doing.",
  ),
  question(
    "sleep",
    "Sleep",
    "lifestyle",
    "How have you been sleeping?",
    "Include usual hours, sleep difficulties, and whether your symptoms affect sleep.",
  ),
  question(
    "nutrition",
    "Nutrition",
    "lifestyle",
    "Is there anything about your diet or appetite you want your provider to know?",
    "Include eating patterns, recent appetite changes, or dietary restrictions.",
  ),
  question(
    "functionalLimitations",
    "Daily activity limitations",
    "lifestyle",
    "How does this concern affect your daily life?",
    "Examples: walking, driving, dressing, work, exercise, or caring for yourself.",
  ),
  question(
    "pcp",
    "Primary care provider",
    "providers",
    "Who is your primary care provider?",
    "Include their name, practice, and contact information if known, or say you do not have one.",
  ),
  question(
    "specialists",
    "Other treating providers",
    "providers",
    "Are you seeing any specialists or other clinicians?",
    "Tell us their names, specialties, and the reason for care, if known.",
  ),
  question(
    "referral",
    "Referral source",
    "providers",
    "Who referred you, or how did you hear about us?",
    "A provider, attorney, friend or family member, internet, or another source.",
  ),
  question(
    "additionalConcerns",
    "Anything else for your provider",
    "providers",
    "Is there anything else you want your provider to know or discuss?",
    "Add questions, concerns, preferences, or anything we have not asked.",
  ),
];

export const HEALTH_SAMPLE =
  "My mother has diabetes and my father had a heart attack at age fifty. My surgical history is an appendectomy in 2012. My hospitalizations include pneumonia in 2018. I do not smoke. My primary care provider is Dr. Alex Rivera. I sleep six hours a night.";
